[manifest] # Header for the file, this should only be here once at the beginning
version = "0.0.1"
priority = 0 # Priority for loading the file

# [[patches]]
# [patches.pattern]
# target = 'functions/state_events.lua' # The file you want to patch.
# pattern = '''
#                 G.FUNCS.draw_from_hand_to_discard()
#                 if G.GAME.blind:get_type() == 'Boss' then
# ''' # The line(s) you want to patch. In pattern patches it should be the whole line(s). Make sure it's unique in that file.
# position = "at" # Where you want to patch it: 'before', 'after' or 'at' (this last one replaces the whole pattern)
# payload = '''
#                 G.FUNCS.draw_from_hand_to_discard()
#                 if G.GAME.tboj_reverse_emperor_used then
#                     G.GAME.tboj_reverse_emperor_used = false
#                 elseif G.GAME.blind:get_type() == 'Boss' then
# ''' # What code you want to replace it with.
# match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.GAME.round_resets.blind_choices.Boss = get_new_boss()"
position = "before"
payload = '''
    G.GAME.round_resets.blind_choices.Small = "bl_small"
    G.GAME.round_resets.blind_choices.Big = "bl_big"
    '''
match_indent = true

# These patches are pulled straight from the Lost Edition mod, they ensure the normal flow of blinds even when Small Blind or Big Blind is replaced with a Boss Blind
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.blind:get_type() == 'Boss' then"
position = "at"
payload = "if G.GAME.blind_on_deck == 'Boss' then"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.round_resets.blind == G.P_BLINDS.bl_small then"
position = "at"
payload = "if G.GAME.blind_on_deck == 'Small' then"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.round_resets.ante == G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' then"
position = "at"
payload = "if G.GAME.round_resets.ante >= G.GAME.win_ante and G.GAME.blind_on_deck == 'Boss' then"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "elseif G.GAME.round_resets.blind == G.P_BLINDS.bl_big then"
position = "at"
payload = "elseif G.GAME.blind_on_deck == 'Big' then"
match_indent = true